<?php
/**
* Anthrocon's authorize.net integration module.
*
* This code is copyright 2008 by Douglas Muth.  Permission is granted
*	to redistribute under the Gnu Public License.
*
*/

/**
* Define our autoloader, and register it.
*/
function authorize_net_autoload($class) {
	//print "$class<br>\n"; // Debugging
	$class = str_replace("_", "/", $class);
	$class = str_replace("authorize/net", "authorize_net", $class);
	//print "$class<br>\n"; // Debugging
	$file = $class . ".class.php";
	//print "$file<br>\n"; // Debugging
	include_once($file);
}

spl_autoload_register("authorize_net_autoload");

/**
* Create our menu items.
*/
function authorize_net_menu($may_cache) {

	$factory = new authorize_net_factory();
	$menu = $factory->get_object("menu");

	$items = $menu->get_menu($may_cache);

	return($items);

} // End of authorize_net_menu()


/**
* Our settings page.
* 
* DO NOT name this authorize_net_settings.  If this function is named
* the same as a the class, it completely breaks under PHP 5.2.4.  I learned 
*	this the hard way.
*/
function authorize_net_settings_page() {

	$reg = new reg();
	$reg->force_ssl();

	$factory = new authorize_net_factory();
	$settings = $factory->get_object("settings");

	return($settings->settings());

} // End of authorize_net_settings()


function authorize_net_settings_form() {

	$factory = new authorize_net_factory();
	$settings = $factory->get_object("settings");

	return($settings->form());
}

function authorize_net_settings_form_validate($form_id, &$data) {

	$factory = new authorize_net_factory();
	$settings = $factory->get_object("settings");

	$settings->validate($form_id, $data);
}

function authorize_net_settings_form_submit($form_id, &$data) {

	$factory = new authorize_net_factory();
	$settings = $factory->get_object("settings");

	$settings->submit($form_id, $data);
}



