<?php
/**
* Anthrocon's authorize.net integration module.
*
* This code is copyright 2008 by Douglas Muth.  Permission is granted
*	to redistribute under the Gnu Public License.
*
*/

/**
* Define our autoloader, and register it.
*/
function authorize_net_autoload($class) {
	//print "$class<br>\n"; // Debugging
	$class = str_replace("_", "/", $class);
	$class = str_replace("authorize/net", "authorize_net", $class);
	//print "$class<br>\n"; // Debugging
	$file = $class . ".class.php";
	//print "$file<br>\n"; // Debugging
	include_once($file);
}

spl_autoload_register("authorize_net_autoload");

/**
* Create our menu items.
*/
function authorize_net_menu($may_cache) {
	$menu = new authorize_net_menu();
	$items = $menu->get_menu($may_cache);
	return($items);
} // End of authorize_net_menu()


/**
* Our settings page.
*/
function authorize_net_settings() {
	$reg = new reg();
	$reg->force_ssl();
	return("Placeholder until I put a form here.");
} // End of authorize_net_settings()




