<?php
/**
* Anthrocon's registration module.
*
* This code is copyright 2008 by Douglas Muth.  Permission is granted
*	to redistribute under the Gnu Public License.
*
* Additional module building info:
*	http://drupal.org/node/82920
*	http://api.drupal.org/
*
*/

/**
* Done:
- Database schema
	- http://api.drupal.org/api/group/database/5
	- db_query(), db_fetch_array()
	- db_lock_table(), db_unlock_tables()
	- db_query_range(), pager_query(), tablesort_sql()

*/


/**
* Load all required files.
* Yeah I like to split my stuff up into smaller "bite sized" files, instead of
* having one large monolithic file.
*/
function reg_load_files() {
	include_once("reg.class.php");
	include_once("reg_admin.class.php");
	include_once("reg_form.class.php");
	include_once("reg_log.class.php");
	include_once("reg_menu.class.php");
	include_once("reg_theme.class.php");
}


function reg_perm() {
	reg_load_files();
	return(reg::perm());
}


/**
* Create our menu items.
*/
function reg_menu($may_cache) {

	reg_load_files();
	$items = reg_menu::menu($may_cache);

	return($items);

} // End of reg_menu()


/**
* Our public registration page.
*/
function reg_registration() {
	reg_load_files();
	return(reg::registration());
}

function reg_registration_form() {
	reg_load_files();
	return(reg_form::reg());
}

function reg_registration_form_validate($form_id, &$data) {
	reg_load_files();
	reg_form::reg_validate($form_id, $data);
}

function reg_registration_form_submit($form_id, &$data) {
	reg_load_files();
	return(reg_form::reg_submit($form_id, $data));
}


/**
* Our settings form.
*/
function reg_admin_settings() {
	reg_load_files();
	return(reg_admin::settings());
}

function reg_admin_settings_form() {
	reg_load_files();
	return(reg_admin::settings_form());
}

function reg_admin_settings_form_validate($form_id, $data) {
	reg_load_files();
	reg_admin::settings_form_validate($form_id, $data);
}

function reg_admin_settings_form_submit($form_id, $data) {
	reg_load_files();
	reg_admin::settings_form_submit($form_id, $data);
}

/**
* Membership level editing stuff.
*/
function reg_admin_levels() {
	reg_load_files();
	return(reg_admin::levels());
}

function reg_admin_levels_edit($id = "") {
	reg_load_files();
	return(reg_admin::levels_edit($id));
}

function reg_admin_level_form($id) {
	reg_load_files();
	return(reg_admin::level_form($id));
}

function reg_admin_level_form_validate($form_id, $data) {
	reg_load_files();
	reg_admin::level_form_validate($form_id, $data);
}

function reg_admin_level_form_submit($form_id, $data) {
	reg_load_files();
	reg_admin::level_form_submit($form_id, $data);
}

/**
* Viewing recent registrations.
*/
function reg_admin_members() {
	reg_load_files();
	return(reg_admin::recent());
}

function reg_admin_members_view($id) {
	reg_load_files();
	return(reg_admin::view($id));
}

function reg_admin_members_edit($id) {
	reg_load_files();
	return(reg_admin::edit($id));
}

/**
* Searching registrations.
*/
function reg_admin_members_search() {
return("This is where our search interface for registrations would be.");
}

/* TEST
function onsitereg_search() {
        $retval = drupal_get_form("onsitereg_search_form");
        $retval .= onsitereg_form::search_results();
        return($retval);
}

function onsitereg_search_form() {
        onsitereg_load_files();
        return(onsitereg_form::search_form());
}

function onsitereg_search_form_validate($form_id, $data) {
        onsitereg_load_files();
        return(onsitereg_form::search_form_validate($form_id, $data));
}

function onsitereg_search_form_submit($form_id, $data) {
        onsitereg_load_files();
        return(onsitereg_form::search_form_submit($form_id, $data));
}
*/

function reg_admin_members_add() {
	reg_load_files();
	return(reg_admin::update());
}

/**
* Viewing logs.
*/
function reg_admin_log() {
	reg_load_files();
	return(reg_log::log());
}

function reg_admin_log_detail($id) {
	reg_load_files();
	return(reg_log::log_detail($id));
}

function reg_admin_trans() {
	reg_load_files();
	return(reg_log::trans());
}

function reg_admin_trans_detail($id) {
	reg_load_files();
	return(reg_log::trans_detail($id));
}

/**
* Viewing registration stats.
*/
function reg_admin_stats() {
return("This is where our stats page would go.");
}


/**
* Our theme function for creating form elements in the reg system.
*/
function theme_reg_theme($form) {
	reg_load_files();
	return(reg_theme::theme($form));
}

/*
include("reg.install");
reg_wipe();
reg_install();
*/

//include_once("reg.class.php");
//echo "TEST";
//echo "badge NUM: " . reg::get_badge_num() . "<br>\n";
//print "TEST2: " . print_r(reg::get_types(), true) . "<br>\n";
//print "TEST3: " . print_r(reg::get_statuses(), true) . "<br>\n";
//print "TEST4: " . print_r(reg::get_cc_types(), true) . "<br>\n";


