<?php
/**
* The Anthrocon Registration "maintenance" module.
* 
* This module can place the registration system into "maintenance" mode so 
* that any attempts to access it give a nice error message.  This is useful 
* for upgrades and deployments.
*
* @author Douglas Muth <http://www.dmuth.org/>
*/


require("settings.inc.php");


/**
* Our main hook.  It runs on every page load.
*/
function reg_maint_init() {

	//
	// Stop here if the module isn't enabled.
	// 
	if (!variable_get("reg_maint_enabled", false)) {
		return(null);
	}

	if (empty($_GET["q"])) {
		$_GET["q"] = "";
	}

	if (preg_match("|^reg|", $_GET["q"])
		|| (
			preg_match("|^admin/reg|", $_GET["q"])
			&& !preg_match("|^admin/reg/maint|", $_GET["q"])
			)
		) {
		print reg_maint_enabled();
		watchdog("reg_maint", "User was shown reg maintenance page.");
		exit();

	}

} // End of reg_autoload()


/**
* This function returns HTML to display when the registration system is in 
* maintenance mode.
*/
function reg_maint_enabled() {

	$retval = ""
		. "<div style=\"font-family: arial; font-size: large;\">"
		. $GLOBALS["conf"]["site_name"]
		. "</div>"
		. "<p/>"
		. "<div style=\"font-family: arial; \">"
		. "If you're seeing this message, the Registration system is in maintenace mode. It will be back shortly!"
		. "</div>"
		. "<p/>"
		;

	$message = variable_get("reg_maint_message", "");

	if ($message) {
		$retval .= ""
			. "<div style=\"font-family: arial; \">"
			. "Admin Message:<p/>"
			. "</div>"
			. "<div style=\"font-family: arial; padding: 20px; background-color: #eeeeee; \">"
			. nl2br($message)
			//. rawurlencode($message) // Debugging
			. "</div>"
			;
	}

	return ($retval);

} // End of reg_maint_enabled()


/**
* This hook is fired when the module is turned on.
*/
function reg_maint_enable() {

	//
	// Disable this module when we enable it, so that the (relatively passive)
	// act of enabling it does NOT take down the registration system.
	//
	variable_set("reg_maint_enabled", false);

	$message = "Reg Maintenance module enabled. Settings page is at /admin/reg/maint";
	drupal_set_message($message);

} // End of reg_maint_enable()


/**
* Create our menu items.
*
*/
function reg_maint_menu() {

	$retval = array();

	$retval["admin/reg/maint"] = array(
		"title" => "Reg Maintenance",
		"type" => MENU_NORMAL_ITEM,
		"page callback" => "reg_maint_settings", 
		"access arguments" => array("administer nodes"), 
		);

	return($retval);

} // End of reg_menu()


